title: Pietro di Caprio
description: 
author: Pietro di Caprio
email: pietro@fabricators.ltd

assets: /assets
uploads: /uploads

permalink: /blog/:title/
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

collections:
  - projects
  - bookmarks
  - contributions

navigation:
    - link: "/"
      name: Me
    - link: "/blog/"
      name: Blog

plugins:
  - jekyll-feed